import Header from "../components/Header";
import SideBar from "./components/SideBar";
import SearchCard from "./components/SearchCard";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Search | OpenTable',
  description: 'Generated by create next app',
}

/* eslint-disable @next/next/no-img-element */
export default function Search() {
  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SideBar />
        <div className="w-5/6">
          <SearchCard />
        </div>
      </div>
    </>
  );
}
