/* eslint-disable @next/next/no-img-element */
import { Metadata } from "next";
import Form from "./components/Form";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: 'Reserve at MilesStone Grills | OpenTable',
  description: 'Generated by create next app',
}

export default function Reservation() {
  return (
    <div className="border-t h-screen">
      <div className="py-9 w-3/5 m-auto">
        <Header />
        <Form />
      </div>
    </div>
  );
}
